pipeline {
    agent any
    tools {
        jdk "defaultJDK"
        maven "maven3.3.9"
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage ('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "--REPOURL--"]]])
            }
        }
        stage ('Compile') {
            steps {
                sh '''
                    pwd
                    mvn compile
                '''
            }
        }
        stage ('Verify') {
            steps {
                sh 'mvn verify'
            }
        }
        stage ('Package') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}
